# Generated by Django 4.0.7 on 2023-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H1', models.CharField(max_length=100)),
                ('H2', models.CharField(max_length=100)),
                ('H3', models.CharField(max_length=100)),
                ('H4', models.CharField(max_length=100)),
                ('H5', models.CharField(max_length=100)),
                ('H6', models.CharField(max_length=100)),
                ('H7', models.CharField(max_length=100)),
                ('H8', models.CharField(max_length=100)),
                ('H9', models.CharField(max_length=100)),
                ('H10', models.CharField(max_length=100)),
                ('H11', models.CharField(max_length=100)),
                ('H12', models.CharField(max_length=100)),
                ('H13', models.CharField(max_length=100)),
                ('H14', models.CharField(max_length=100)),
                ('H15', models.CharField(max_length=100)),
                ('H16', models.CharField(max_length=100)),
                ('H17', models.CharField(max_length=100)),
                ('H18', models.CharField(max_length=100)),
                ('H19', models.CharField(max_length=100)),
                ('H20', models.CharField(max_length=100)),
                ('H21', models.CharField(max_length=100)),
                ('H22', models.CharField(max_length=100)),
                ('H23', models.CharField(max_length=100)),
                ('H24', models.CharField(max_length=100)),
                ('H25', models.CharField(max_length=100)),
                ('H26', models.CharField(max_length=100)),
                ('H27', models.CharField(max_length=100)),
                ('H28', models.CharField(max_length=100)),
                ('H29', models.CharField(max_length=100)),
                ('H30', models.CharField(max_length=100)),
                ('H31', models.CharField(max_length=100)),
                ('H32', models.CharField(max_length=100)),
                ('H33', models.CharField(max_length=100)),
                ('H34', models.CharField(max_length=100)),
                ('H35', models.CharField(max_length=100)),
                ('H36', models.CharField(max_length=100)),
                ('H37', models.CharField(max_length=100)),
                ('H38', models.CharField(max_length=100)),
                ('H39', models.CharField(max_length=100)),
                ('H40', models.CharField(max_length=100)),
                ('H41', models.CharField(max_length=100)),
                ('H42', models.CharField(max_length=100)),
                ('H43', models.CharField(max_length=100)),
                ('H44', models.CharField(max_length=100)),
                ('H45', models.CharField(max_length=100)),
                ('H46', models.CharField(max_length=100)),
                ('H47', models.CharField(max_length=100)),
                ('H48', models.CharField(max_length=100)),
                ('H49', models.CharField(max_length=100)),
                ('H50', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table_Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
