# Generated by Django 4.0.7 on 2023-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('h2', models.CharField(max_length=100)),
                ('h3', models.CharField(max_length=100)),
                ('h4', models.CharField(max_length=100)),
                ('h5', models.CharField(max_length=100)),
                ('h6', models.CharField(max_length=100)),
                ('h7', models.CharField(max_length=100)),
                ('h8', models.CharField(max_length=100)),
                ('h9', models.CharField(max_length=100)),
                ('h10', models.CharField(max_length=100)),
                ('h11', models.CharField(max_length=100)),
                ('h12', models.CharField(max_length=100)),
                ('h13', models.CharField(max_length=100)),
                ('h14', models.CharField(max_length=100)),
                ('h15', models.CharField(max_length=100)),
                ('h16', models.CharField(max_length=100)),
                ('h17', models.CharField(max_length=100)),
                ('h18', models.CharField(max_length=100)),
                ('h19', models.CharField(max_length=100)),
                ('h20', models.CharField(max_length=100)),
                ('h21', models.CharField(max_length=100)),
                ('h22', models.CharField(max_length=100)),
                ('h23', models.CharField(max_length=100)),
                ('h24', models.CharField(max_length=100)),
                ('h25', models.CharField(max_length=100)),
                ('h26', models.CharField(max_length=100)),
                ('h27', models.CharField(max_length=100)),
                ('h28', models.CharField(max_length=100)),
                ('h29', models.CharField(max_length=100)),
                ('h30', models.CharField(max_length=100)),
                ('h31', models.CharField(max_length=100)),
                ('h32', models.CharField(max_length=100)),
                ('h33', models.CharField(max_length=100)),
                ('h34', models.CharField(max_length=100)),
                ('h35', models.CharField(max_length=100)),
                ('h36', models.CharField(max_length=100)),
                ('h37', models.CharField(max_length=100)),
                ('h38', models.CharField(max_length=100)),
                ('h39', models.CharField(max_length=100)),
                ('h40', models.CharField(max_length=100)),
                ('h41', models.CharField(max_length=100)),
                ('h42', models.CharField(max_length=100)),
                ('h43', models.CharField(max_length=100)),
                ('h44', models.CharField(max_length=100)),
                ('h45', models.CharField(max_length=100)),
                ('h46', models.CharField(max_length=100)),
                ('h47', models.CharField(max_length=100)),
                ('h48', models.CharField(max_length=100)),
                ('h49', models.CharField(max_length=100)),
                ('h50', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
