# Generated by Django 4.0.7 on 2023-12-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex_upload', '0002_table_e_h51_table_e_h52_table_e_h53'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_e',
            name='timestamp',
        ),
    ]
